### ISSUE TITLE
Associate a spree_order with a taxjar transaction ID

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#101]
An order in solidus can potentially have multiple transaction ID if it is refunded partially.

These transaction ID's will have sequential numbering, i.e. `order-number-transaction-1`, `order-number-transaction-2`, `order-number-transaction-3`. 

We want to ...

1. Associate these transaction ID's with the order, and
2. Be able to retrieve the latest transaction ID associated with the order

**Comment by Noah-Silvera** [comment]
We should also update the default `transaction_id` used in the `transaction_params` to be the current associated transaction id once this work is completed!

**Comment by Noah-Silvera** [comment]
We should decorate the spree order with a `latest_created_taxjar_transaction` method to return the latest `taxjar_transaction` that was created (not refunds) and use this in the various locations we currently use the `order.number` as the transaction_id.

**Comment by forkata** [comment]
@Noah-Silvera Is there an API we can create which doesn't require us to decorate the `Spree::Order` model. I feel like adding more methods to `Order` is rarely the right answer? Maybe we can introduce a `Reporting` specific class which can give us all transactions, just the last one, refund transactions for a given order.

**Comment by Noah-Silvera** [comment]
> @Noah-Silvera Is there an API we can create which doesn't require us to decorate the `Spree::Order` model. I feel like adding more methods to `Order` is rarely the right answer. Maybe we can introduce a `Reporting` specific class which can give us all transactions, just the last one, refund transactions, etc. for a given order. I feel like we may need more functionality in the future and starting down this path would probably mean more methods we decorate the `Order` with.

You solved this problem nicely Chris with adding a method to the `TaxjarTransaction` model!

https://github.com/SuperGoodSoft/solidus_taxjar/blob/2b12eaef399f4fc681db9da9588b40dcb6567e1c/app/models/super_good/solidus_taxjar/order_transaction.rb#L9

**Comment by Noah-Silvera** [comment]
> We should also update the default transaction_id used in the transaction_params to be the current associated transaction id once this work is completed!

`ApiParams.transaction_params` is only used in two places. One of those places (`create_transaction_for`) has been updated to use the latest transaction id, which is appropriate. The other place (`update_transaction_for`) is an API call we don't currently plan to use in our default reporting implementation, and shouldn't change unnecessarily at this point, as it is a public API others may be relying on for their own reporting implementation.
