### ISSUE TITLE
Allow checking whether TaxJar has up-to-date order totals

### ISSUE THREAD

**Issue by benjaminwil** [SuperGoodSoft/solidus_taxjar#106]
In order to determine whether to update the associated transaction on TaxJar for an order, we need to create a service/API/method which will do the following

1. Pull the associated transaction on TaxJar for the order
2. Compare the values of the TaxJar transaction to the current values on the solidus order
3. Determine whether those values have changed and the transaction for the order needs to be updated #112

**Comment by forkata** [comment]
We are still unsure if this will be necessary in order to reduce the number of API calls we make to TaxJar to refund and re-create a transactions so this is on HOLD for now.

**Comment by Noah-Silvera** [comment]
I think this will be needed at the very least for #124, as we will need to determine whether to sync a transaction when we are backfilling

**Comment by Noah-Silvera** [comment]
Some background on this issue can be found in #112

**Comment by Noah-Silvera** [comment]
@benjaminwil are you completing this work as part of #92 or is #92 going to initially be naive and just always post an update?

**Comment by benjaminwil** [comment]
@Noah-Silvera Yes, I am working on this!

**Comment by benjaminwil** [comment]
Just moved its project status.

**Comment by benjaminwil** [comment]
This issue is resolved in the referenced merged PRs.
