### ISSUE TITLE
Provide a way to stub taxes in "test_mode"

### ISSUE THREAD

**Issue by forkata** [SuperGoodSoft/solidus_taxjar#110]
The default behaviour of the gem is to returns no tax when configured in "test_mode". Additionally when the gem is configured in "test_mode" it is not easy to stub and provide a fake response when calculating taxes, so it may be beneficial if we provide some examples and maybe an easier way to achieve this in order to facilitate testing of client applications using this gem.

**Comment by jarednorman** [comment]
Maybe you could elaborate on what you'd like to see? I don't understand.

**Comment by forkata** [comment]
It would be nice if we can provide some direction in terms of how you can pre-configure a response for a non-zero tax rate when the gem is in `test_mode`.

**Comment by forkata** [comment]
To elaborate a bit further, we have an easy way to configure the API client used by our tax calculator as we do in our tests here https://github.com/SuperGoodSoft/solidus_taxjar/blob/236689547619b00c5822a745fe5b739932425bcf/spec/super_good/solidus_taxjar/tax_rate_calculator_spec.rb#L7 however there is an early return for when the gem is in `test_mode` https://github.com/SuperGoodSoft/solidus_taxjar/blob/236689547619b00c5822a745fe5b739932425bcf/lib/super_good/solidus_taxjar/tax_calculator.rb#L12 which prevents us from using that to setup test responses. There may be an obvious thing I am missing here and if there is it would be great to add that to the readme.

**Comment by jarednorman** [comment]
In what situation do you want to reach into the gem and play with different responses? There are better ways to test different taxation _results_ (your own test calculator, stubbing, etc.) that don't couple you to the implementation of this gem. When would you care about testing specific responses coming back from the API, rather than just different tax results in the context of a client application?

It might be useful if you provided an example test that you want to be able to write, but can't.

**Comment by forkata** [comment]
> In what situation do you want to reach into the gem and play with different responses? There are better ways to test different taxation results (your own test calculator, stubbing, etc.) that don't couple you to the implementation of this gem.

Stubbing the calculator is the direction we went but I was hoping for a simpler solution, as that involves building out the full response from the calculator in the test in question. What I was hoping for here is a mechanism to provide an alternative to the `no_tax` response we return in `test_mode` but with a pre-configured tax rate for all line items or shipments.

As you suggested there are a number of ways to do that outside of what this gem provides, either by creating a test calculator or falling back to the Solidus tax system provided in core and setting things up in test. All of these options are completely valid and I think it's reasonable to recommend users go that route if we don't want to provide an alternative as part of this gem. I've personally always found setting up a test order with taxes correctly to be tricky, and always end up having to open up and debug the internals of the tax system, so I see this as an opportunity for us to provide some better testing support than what we get from Solidus out of the box.

**Comment by jarednorman** [comment]
I agree that better support for that would be nice; I've wanted to create a gem that just provided something like:

```ruby
class DummyTaxCalculator
  def self.new_calculator_class(tax_percent:, tax_shipments: false)
    Class.new(self).tap do |klass|
      klass.tax_percent = tax_percent
      klass.tax_shipments = tax_shipments
    end
  end

  class_attribute :tax_percent
  class_attribute :tax_shipments
 
  def initialize(order)
    @order = order
  end

  def calculate
    Spree::Tax::OrderTax.new(
      order_id: @order.id,
      line_item_taxes: @order.line_items.map { |line_item|
        Spree::Tax::ItemTax.new(
          item_id: line_item.id,
          label: "Sales Tax",
          tax_rate: some_kind_of_find_or_create_thing,
          included_in_price: false,
          amount: line_item.amount * tax_percent
        )
      },
      shipment_taxes: if tax_shipments?
           @order.shipments.map { |shipment|
             Spree::Tax::ItemTax.new(
               item_id: shipment.id,
               label: "Sales Tax",
               tax_rate: some_kind_of_find_or_create_thing,
               included_in_price: false,
               amount: shipment.amount * tax_percent
             )
           }
        else
           []
        end
    )
  end
end
```

I don't think that support for this has anything to do with TaxJar though, so I think it should be offered outside this extension. I wouldn't want my tests that are decoupled from my tax calculation backend to be unnecessarily coupled to it because they come from the same gem.

**Comment by forkata** [comment]
Thanks for providing this example, I think it will be useful for others looking for a way to setup an order with taxes.
