### ISSUE TITLE
Add descriptive text that explains how the backfilling UI works.

### ISSUE THREAD

**Issue by benjaminwil** [SuperGoodSoft/solidus_taxjar#152]
As an end user, I would like to understand how the backfilling feature works so I can use it effectively.

## Acceptance criteria

Descriptive text on the page that gives the user a general idea of how the feature works, i.e. that the filter is based on updated at, that this will post transactions to TaxJar or update them if they already exist and need to be updated, etc.

**Comment by Noah-Silvera** [comment]
Note: We should also be sure to stress in the docs that you really **really** should backfill when setting up this extension

**Comment by benjaminwil** [comment]
I did this here: https://github.com/SuperGoodSoft/solidus_taxjar/wiki/Reporting
