### ISSUE TITLE
Display and sync existing TaxJar nexus regions in the Solidus admin

### ISSUE THREAD

**Issue by benjaminwil** [SuperGoodSoft/solidus_taxjar#156]
As a Solidus admin user, I want to see Nexus regions already configured in TaxJar so that I know what TaxJar Nexus regions can be used.

## Additional information
- We always need fresh TaxJar Nexus region data from TaxJar.
- Maybe a "sync" button just refreshes the page and calls out to TaxJar again.
- Don't cache Nexus regions if possible.

**Comment by forkata** [comment]
@benjaminwil Do we plan on persisting this data in Solidus or will this view be only populated on clicking `Sync`? Now that we have a configuration table we are adding in #138 I am wondering if we can't use a new row in the preferences column to serialize and store this data, maybe a stretch for that table 🤔

**Comment by benjaminwil** [comment]
@forkata Can we implement without persisting them for the sake of this ticket?

@Noah-Silvera made an observation that we never want to accidentally use an out-of-date nexus region. And we thought that the safest way to ensure that is to request them fresh every time we need them.

After we make this naive implementation, maybe we can more confidently find ways to optimize.

**Comment by forkata** [comment]
Yeah, totally, this was only a question. We shouldn't have to worry about using out-dated regions because this should not be sent in the payload to get taxes, if I understand this correctly it's just an interface for users to manage their nexuses through the solidus UI, instead of on TaxJar. We can always force them to fetch before creating or something like that.

My understanding is that we only need to send Nexus regions in the API call to get taxes if we want to override what is configured in TaxJar, which is not what we're doing here.

**Comment by benjaminwil** [comment]
Right, that is my understanding as well.

**Comment by Noah-Silvera** [comment]
We will be doing a taxable address check using nexus regions before making a tax calculation, as part of this ticket!

https://github.com/SuperGoodSoft/solidus_taxjar/issues/57

I think when we get to that we may want to consider caching nexus regions in some way, but probably on a short term basis, and not with database persistence.

**Comment by forkata** [comment]
@Noah-Silvera Interesting, I didn't realize that was the motivation for this 👍🏼

**Comment by Noah-Silvera** [comment]
After the meeting with Ryan, we learned that we can either a.) store the nexus regions locally and make a user manually sync them when they add new nexus regions on the taxjar site or b.) automatically keep the list of nexus regions up to date, potentially with a short lived cache.
Both strategies have been implemented by different integration partners
