### ISSUE TITLE
Add new TaxJar nexus regions in the Solidus admin

### ISSUE THREAD

**Issue by benjaminwil** [SuperGoodSoft/solidus_taxjar#157]
As a Solidus admin users, I want to be able to quickly add new nexus regions so that I don't have to do this from the TaxJar website.

## Additional information

- TaxJar is definitely still the source of truth for Nexus regions.
- This is a certification requirement.
- We really don't want to dupe Nexus regions, obviously.

**Comment by senemsoy** [comment]
The TaxJar API has no method for adding new Nexus regions. https://developers.taxjar.com/api/reference/#nexus

**Comment by Noah-Silvera** [comment]
Huh... that's strange. Magento definitely seems to be able to do it, unless their "add new nexus address" button is just a link to taxjar!

![image](https://user-images.githubusercontent.com/8933450/155598511-18b5640d-1a21-40c5-b5c4-bb2d248507c6.png)


My understand is that adding new nexus regions was a certification requirement (nexus management), so maybe we should check what the magento integration does as a guideline and/or checkin with Ryan!

**Comment by benjaminwil** [comment]
@Noah-Silvera We read through the certification requirements and we don't see that requirement anywhere. Where did you see it?

Convenience link: https://developers.taxjar.com/integrations/certification-checklist/

**Comment by senemsoy** [comment]
@Noah-Silvera I think it is indeed a link to TaxJar, which is a certification requirement: _Provide a link to their TaxJar account State settings (https://app.taxjar.com/account#states)._

<img width="719" alt="Screen Shot 2022-02-24 at 12 06 14 PM" src="https://user-images.githubusercontent.com/16298232/155599215-01816d03-9303-45e6-a3c9-f48e6e99a16b.png">

I think this is not a part of the certification requirement but could be wrong!

**Comment by Noah-Silvera** [comment]
I think y'all are right and I was getting confused by the Magento integration having support for adding nexus regions in app

https://github.com/taxjar/taxjar-magento2-extension/blob/cf82eef706b91bc1d28d2994ca3d29a7c2936dbf/Block/Adminhtml/Tax/Nexus/Edit/Form.php#L114

But it doesn't seem like it's required.
