### ISSUE TITLE
Handle refunding an order that has never been reported to Taxjar

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#162]
After talking to Ryan, we discovered the following should happen when you refund an order that has never been reported to Taxjar.

- Show the admin user a warning that they should backfill their orders
- Just post a "Refund" type transaction with the amount of the refund and no link to an existing order transaction

**Comment by Noah-Silvera** [comment]
https://github.com/SuperGoodSoft/solidus_taxjar/blob/45d3ceb407fea96d1be391d1319d92df2aea84f7/lib/super_good/solidus_taxjar/api.rb#L75

**Comment by Noah-Silvera** [comment]
cc: @Noah-Silvera  @nvandoorn backfilling needs to consider this scenario

**Comment by Noah-Silvera** [comment]
Note: We need to know the state of an order before and after it is updated in order to determine if it is a refund.
* `order_recalculated` provides this, **but** if the event is sent **async** in Solidus 3.2 plus, this behavior is null

We thought about hooked into `reimbursement_reimbursed`, but this doesn't cover all refund cases. We might be able to hook into that and a custom event for hitting the "refund" button on a payment and be covered, but we are not sure

**Comment by Noah-Silvera** [comment]
Alternate idea - blowup

**Comment by Noah-Silvera** [comment]
One idea: 

We should blowup **and document this**

* For any transactions that are changed (and paid and shipped) outside of a period where TaxJar syncing was on, we should blow up.
* To do this, we will a.) need to know when TaxJar syncing was on
* b.) Display some obvious error message to a user asking them to manually report it
* c.) Fake a transaction sync log with a permanent version of an errors message

Second Idea;

* Try to use the order changeset to report an original transaction (and report it **in the past**), automatically backfill it, and then report a refund **in the present**
* We probably need to contact taxjar about this
* We could also look at magento implementation

**Comment by Noah-Silvera** [comment]
Summarize
- We want to go with option a.) Blowing up

Implementation Details we talked about
- Reporting this error to the configurable taxjar error handler (least noisy, would want to make sure in the docs people are aware of this handler and hook into it)
- Blowing up the job when this happens, and letting the built in error handling system take care of it.

We still haven't fully figured on how to determine what orders will cause this blowup. (i.e. if an order that is paid/shipped has been previously reported or should be reported currently. Need to consider additional payments/refunds)

**Comment by nvandoorn** [comment]
Some work in progress work here https://github.com/SuperGoodSoft/solidus_taxjar/tree/162-handle-refunding-order-with-no-backfill

**Comment by Noah-Silvera** [comment]
Note from our meeting
- We should just report the error the internal configurable error handler, and not blow up, to prevent order updates from failing

**Comment by Noah-Silvera** [comment]
We actually already document that we don't support this use case [in our docs](https://github.com/SuperGoodSoft/solidus_taxjar/wiki/Reporting)

> This means syncing an unreported order that is being refunded or recalculated will fail. To remedy this you can use [the backfill order interface](https://github.com/SuperGoodSoft/solidus_taxjar/wiki/Reporting#Backfilling-reported-orders) to first sync the historical orders that you may want to re-report in the future.

So honestly this feels like an enhancement at this point, and we should be able to remove it out of the 1.0 release

cc: @benjaminwil @forkata feel free to move it back into the 1.0 if you feel we should!
