### ISSUE TITLE
Tax amount is incorrect when re-reporting an order to TaxJar

### ISSUE THREAD

**Issue by nvandoorn** [SuperGoodSoft/solidus_taxjar#184]
Here is a demo showing:
- A user purchasing several items
- An admin shipping the items
- An admin cancelling one of the items because the order was short shipped.

The video shows the three transactions reported to TaxJar:

1) The original transaction
2) The refund for the original
3) The replacement transaction with the adjusted amount, but incorrect tax amount ($6.15 tax, higher than the original $4.10)

[taxjar.log](https://github.com/SuperGoodSoft/solidus_taxjar/files/8523770/taxjar.log)
https://user-images.githubusercontent.com/1747836/164287227-985dddab-9523-4ca3-b883-5756f2802bf3.mp4

**Comment by Noah-Silvera** [comment]
This may be fixed by https://github.com/SuperGoodSoft/solidus_taxjar/pull/181 but needs retesting!
