### ISSUE TITLE
Documentation before 1.0 Release

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#207]
## Table of all available configuration options

* [x] What they do
* [x] What the defaults are
* [x] Add a warning about using the `taxable_order_hook` https://github.com/SuperGoodSoft/solidus_taxjar/issues/50

## Nexuses

* [ ] The nexus sync button and when to use it.

## Reporting

* [x] Walkthrough - how do you setup reporting/go through backfill/confirm it works
* [x] When does a transaction get reported
* [x] When does a refund transaction get reported
* [x] Note that reporting is turned off by default.
* [x] Why order-level adjustments are unsupported
* [x] Backfilling historical orders safely

## Changelog

* [x] Pull breaking changes out of changelog into release notes
* [x] Refactor changelog to be more organized
* [x] Bug fixes, breaking changes, new features, high level summary. Re: Solidus or other projects

## Other

* [x] ~~Note that purchasing gift cards is not taxable, **do not report them.**~~

**Comment by Noah-Silvera** [comment]
Note: We should probably put this stuff in the wiki

Someone will have to refactor the Readme to move non-relevant documentation into the wiki

**Comment by benjaminwil** [comment]
> Note: We should probably put this stuff in the wiki

For now, I've made a pull request, #210, to add the configuration settings to the README.

One thing I _don't_ like about GitHub wikis is that there's no way to version them alongside the code. For developer configuration settings, at least, this makes me think the README, or some other committed document, is the best place to describe the settings.

For reporting interface usage and documentation–the wiki might be a more appropriate place.

**Comment by benjaminwil** [comment]
Added an item to the list in the original issue post: "Nexus sync button and when to use it."

**Comment by benjaminwil** [comment]
Just refactored the list and checked off things that are documented in the README and on the wiki already.

**Comment by benjaminwil** [comment]
> Add a warning about using the `taxable_order_hook`

@Noah-Silvera I am not sure how to document this. From the original ticket it seems like you have an idea of how to.

**Comment by benjaminwil** [comment]
> Note that purchasing gift cards is not taxable, **do not report them.**

@forkata @Noah-Silvera Is this in-scope? Solidus doesn't provide gift cards by default, so I think it would be up to each store and its development team to handle this their own way.

**Comment by forkata** [comment]
@benjaminwil I don't think GC's are in scope since like you said it's not a feature Solidus provides out of the box.
