### ISSUE TITLE
uninitialized constant Deface

### ISSUE THREAD

**Issue by diegomichel** [SuperGoodSoft/solidus_taxjar#212]
In case someone runs into the same issue:

```
.rvm/gems/ruby-3.0.2@project/gems/super_good-solidus_taxjar-0.18.2/app/overrides/spree/admin/shared/_configuration_menu.rb:3:in `<main>': uninitialized constant Deface (NameError)
```

workaround: add this to your Gemfile project:

```
gem 'deface'
```

**Comment by forkata** [comment]
Good call on this, we should add this to the gemspec of this extension! It looks like we're getting it in the dummy app against which we run tests from `solidus_auth_device` and that's why we never realized we need to explicitly depend on that!

**Comment by diegomichel** [comment]
@forkata I tried to add it to the `gemspec`, then I had to require it manually on the view, but after that, I ran into other issues

```
.../bundler/gems/solidus_taxjar-8e81b0375cb1/app/overrides/spree/admin/shared/_configuration_menu.rb to define constant Spree::Admin::Shared::ConfigurationMenu, but didn't (Zeitwerk::NameError)   
```

https://github.com/SuperGoodSoft/solidus_taxjar/compare/master...diegomichel:solidus_taxjar:master

For now the workaround will do :)

**Comment by forkata** [comment]
This is now fixed! Thanks @benjaminwil!
