### ISSUE TITLE
Overrides loading multiple times

### ISSUE THREAD

**Issue by diegomichel** [SuperGoodSoft/solidus_taxjar#214]
Adding `solidus_taxjar` to my project makes files under `app/overrides/` load two more extra times after it has been loaded initially.

I get messages like 
```
warning: already initialized constant ...
```

**Comment by forkata** [comment]
Hey @diegomichel! Thank you for opening this issue. Could you provide some details regarding your Rails/Solidus and `solidus_taxjar` gem version?

This extension doesn't do anything specific regarding loading files from `app/overrides` other than what is provided by Solidus itself. Depending on what version of Solidus you are running, you may want to confirm if you don't have some configuration or code which is explicitly loading files from that path. There are some notes on this relating to Solidus 3.2 and Rails 7 you can take a look in the Solidus documentation - https://github.com/solidusio/solidus/blob/88592ef79eef49bbd7f7a4f3afc0857dd0722709/CHANGELOG.md#other-important-changes

**Comment by diegomichel** [comment]
Thanks, @forkata 

```
rails (7.0.4.1)
solidus (3.2.2)
super_good-solidus_taxjar (0.18.2) (Master branch revision: 38f31ed0bce5add61cd6a50654fe97b60aa5ae5d)
```

My `application.rb` reflects what's described on the link you shared.

I added a little debug message on the overrided class to print the times it loaded, without `solidus_taxjar` prints once, with `solidus_taxjar` installed, it prints three times. It might be something related to my configuration tho, not sure.

I will try to repro with a clean project.

**Comment by diegomichel** [comment]
My apologies @forkata,

I printed `caller` on the override file, and these are the outputs of each; even before installing `solidus_taxjar`, it looks like `deface` loads it twice. (it's the first print on the left)

<img width="1837" alt="Screenshot 2023-01-25 at 15 41 56" src="https://user-images.githubusercontent.com/848433/214708760-59d92d6c-a632-4a0c-8ba7-1c6cf995cdc0.png">

Skipping the settings.rb changes directed on https://guides.solidus.io/customization/customizing-the-core/#using-overrides makes it load only once. 😕

**Comment by diegomichel** [comment]
The issue is on Deface gem. Bug report(with workaround by @waiting-for-dev) on solidus repo for reference: https://github.com/solidusio/solidus/issues/4877
