### ISSUE TITLE
Support for Canada

### ISSUE THREAD

**Issue by cmhnk** [SuperGoodSoft/solidus_taxjar#25]
Hey there!

I noticed that as of about 3 months ago, `solidus_taxjar` is only supporting US addresses (commit [here](https://github.com/SuperGoodSoft/solidus_taxjar/blame/master/lib/super_good/solidus_taxjar/addresses.rb#L35)). However, the TaxJar API itself does have [support for Canada](https://support.taxjar.com/article/22-does-taxjar-support-vat-or-canada) and other countries.

Is the current suggested approach to use `SuperGood::SolidusTaxJar.custom_order_params`, or would you be open to a pull request to update `SuperGood::SolidusTaxJar::Addresses` to support tax estimation for other countries? If there are any complications or context worth understanding about the latter approach, I'd be curious to hear your thoughts!

Thanks,
-Corinne

**Comment by jarednorman** [comment]
Thanks for opening this issue @cmhnk and sorry for the slow reply!

I think if would be only a small change to `SuperGood::SolidusTaxJar::Addresses` to make this work.

As a Canadian myself, I would welcome a PR that updates that method to use the country code returned by the TaxJar API. 😄🇨🇦

**Comment by cmhnk** [comment]
Awesome, I'll take a look later this week and see if I can get a PR up. Thanks @jarednorman !

**Comment by cmhnk** [comment]
After some further investigation, I learned two key things about TaxJar's address validation. 

1) The address validation endpoint is not available in the TaxJar sandbox; [their docs](https://developers.taxjar.com/api/reference/#post-validate-an-address) specify that "Address validation requires a TaxJar Professional or higher subscription." If using the sandbox api, you'll get:
`Taxjar::Error::NotFound (No such route 'POST /v2/addresses/validate')`

2) The TaxJar API _itself_ does not support address validation outside of the U.S. I originally misunderstood and thought a simple change to this gem was all that would be needed. If you attempt to validate a non-U.S. address, TaxJar returns:
`Taxjar::Error::Forbidden (Only US addresses can be validated at this time)`

---

Based on this information, I'm tempted to close this issue since it doesn't seem like there's much to be done at this time with respect to address validation in Canada. 

However, I did want to mention a separate but related issue – namely, tax rate estimation in Canada.

 I'm seeing tax rates for Canada addresses returned as 0, which if I'm not mistaken should be something like [13%](https://www.fin.gov.on.ca/en/tax/hst/index.html#:~:text=The%20Harmonized%20Sales%20Tax%20(HST)%20is%2013%25%20in%20Ontario,a%20point%20of%20sale%20rebate.). 

```
address = Spree::Address.create(firstname: 'Corinne', lastname: 'H', address1: '100 Queen St W', city: 'Toronto', state: Spree::State.find_by(name: 'Ontario'), country: Spree::Country.find_by(name: 'Canada'), zipcode: 'M5h2N1', phone: '1234567890')

SuperGood::SolidusTaxJar::API.new.tax_rate_for(address)
=> 0.0
```
Wanted to get your thoughts on this, @jarednorman – does this seem like a bug that should be investigated further?

**Comment by jarednorman** [comment]
Address validation might not work, but I think that tax calculation should. Do you have a Canadian/Ontarian Nexus location configured?

**Comment by cmhnk** [comment]
Hmm admittedly I don't know much about Nexus locations – but I'm just using the TaxJar sandbox API at the moment. I've verified that I'm able to get the correct amount via curl, which leads me to believe the sandbox account is set up with the necessary nexus configuration. 

### Root Issue:
...After some squinting, I've realized that the issue is that `SuperGood::SolidusTaxJar::API#tax_rates_for` works as expected, but `tax_rate_for` returns 0. 

```
SuperGood::SolidusTaxJar::API.new.tax_rate_for(address)
=> 0.0

SuperGood::SolidusTaxJar::API.default_taxjar_client.rates_for_location(*SuperGood::SolidusTaxJar::APIParams.address_params(address))
=> #<Taxjar::Rate zip: "M5H2N1", state: "ON", state_rate: nil, county: nil, county_rate: nil, city: "Toronto", city_rate: nil, combined_district_rate: nil, combined_rate: 0.13, freight_taxable: true, country: "CA", name: nil, country_rate: nil, standard_rate: nil, reduced_rate: nil, super_reduced_rate: nil, parking_rate: nil, distance_sale_threshold: nil>
```

Should [tax_rate_for](https://github.com/SuperGoodSoft/solidus_taxjar/blob/master/lib/super_good/solidus_taxjar/api.rb#L25) actually take the `Spree::Order` as an argument rather than a `Spree::Address`, since it calls `Taxjar::Client#tax_for_order`? I believe as it's currently written, `SuperGood::SolidusTaxJar::API.new.tax_rate_for` will always return 0, since we're only passing an address (and [not line items, nexus_addresses, etc](https://github.com/taxjar/taxjar-ruby#example-request-1)).

**Comment by jarednorman** [comment]
If you don't have nexus in a given location (i.e. a physical presence) then you don't typically charge tax in that region. That's true for Canada and _mostly_ true for the US.

I'm not 100% why you're seeing the result you're seeing for the `#tax_rate_for` method, but the the `#tax_for` method is the one that is relied on for order tax calculation. That one takes an order and returns the taxes for it. If you've configured a Canadian Nexus in TaxJar then that one should work.

`#tax_rate[s]_for` is a convenience method for providing tax estimates and things when you don't have full order information. It's not what the tax calculator actually uses to compute the taxes.

**Comment by cmhnk** [comment]
Hey @jarednorman - sorry for the slow reply, and thank you for your detailed reply! Everything you're saying makes sense.

This is definitely a separate issue from the original "Support Canada" idea, but I think it might be worth removing the `SuperGood::SolidusTaxJar::API#tax_rate_for` method, to prevent others from experiencing the same confusion I did. 

Bug:
- Call `SuperGood::SolidusTaxJar::API#tax_rate_for` with any address at all. It will always return 0. The reason is that this method is wrapping a call to [Taxjar::API#tax_for_order](https://github.com/taxjar/taxjar-ruby/blob/master/lib/taxjar/api/api.rb#L15), which, if called without order information, will return 0.

I believe anyone needing a convenience method for getting tax estimates without order info should be able to use `SuperGood::SolidusTaxJar::API#tax_rates_for` successfully, since that wraps [Taxar::API#rates_for_location](https://github.com/taxjar/taxjar-ruby/blob/master/lib/taxjar/api/api.rb#L11) which does not depend on order info.

I can submit a PR if you're open to it, otherwise I can close this issue. Let me know what you prefer, and thank you again for all your help!

**Comment by jarednorman** [comment]
That method is used by `SuperGood::SolidusTaxJar::TaxRateCalculator` and I'm 99% sure that it doesn't always return zero because it's in use in at least one of our production applications. It returning non-zero values is however dependent on the nexuses you have configured in TaxJar.

**Comment by cmhnk** [comment]
Ah okay, my bad! Closing this issue.

**Comment by jarednorman** [comment]
No problem!
