### ISSUE TITLE
Testing Before 1.0 Release

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#251]
# 1.0 Release Testing

On a solidus store, with reporting and sidekiq set up, run the following Tests
**Use the documentation when performing these tests and the initial setup to test the docs**

* [x] Create at least 2 shipped orders before enabling the integration
* [x] Enable the integration
* [x]  Complete and ship orders, and ensure they get synced to taxjar
* [x] Refund an order (with a return), ensure it gets synced to taxjar
* [x] Fake errors in the reporting process at every stage (initial report, refund, re-report), and ensure you can manually retry the sync and it succeed
* [x]  Backfill the 2 shipped orders that were completed before enabling the integration
* [x] Test the nexus region sync feature

**Comment by Noah-Silvera** [comment]
- Returning an item failed, because the reimbursement was calculated with the wrong tax amount

**Comment by benjaminwil** [comment]
We completed testing.
