### ISSUE TITLE
The Spree::Address#address2 attribute is ignored during address validation

### ISSUE THREAD

**Issue by jasonwmatthews** [SuperGoodSoft/solidus_taxjar#28]
The `SuperGood::SolidusTaxJar::APIParams` module does not include the `Spree::Address#address2` attribute when constructing the `street` parameter for TaxJar's API. The `street` parameter is defined as the "[freeform input](https://developers.taxjar.com/api/reference/#post-validate-an-address)" indicating the two Solidus address fields should be concatenated if both are populated.

Omitting the `address2` attribute can result in slightly different normalized addresses where an apartment number, mail stop, or other unit information has a unique ZIP+4 code.

One fairly large example, One World Trade Center in New York has around 40 unique ZIP+4 codes, depending on floor or suite number:

1 WORLD TRADE CTR
NEW YORK NY 10007-0089

1 WORLD TRADE CTR STE 45A
NEW YORK NY 10007-0093

1 WORLD TRADE CTR FL 50
NEW YORK NY 10007-0101

1 WORLD TRADE CTR FL 99
NEW YORK NY 10007-0089

**Comment by Noah-Silvera** [comment]
This was released in 0.18.2
