### ISSUE TITLE
Migrate to CircleCI and official Solidus orb

### ISSUE THREAD

**Issue by aldesantis** [SuperGoodSoft/solidus_taxjar#46]
In order to ensure the extension is always compatible with the currently maintained Solidus versions, I'd recommend migrating it to CircleCI and the [solidusio/extensions](https://circleci.com/developer/orbs/orb/solidusio/extensions) orb, so that we don't have to maintain the list of Solidus versions manually and so that the extension is periodically tested against master, to ensure it's compatible with the upcoming Solidus version.

**Comment by Noah-Silvera** [comment]
This is done!
