### ISSUE TITLE
The taxable_order hook should document a warning around skipping transactions

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#50]
~~According to the [Certifcation guidelines](https://developers.taxjar.com/integrations/certification-checklist/), all US based transactions need to be pushed. For that reason, we should prevent consumers from overriding the taxable_order hook with a function that skips US transactions.~~

Reworking this ticket based on the discussion below.

We should document this configuration option and the caveat that you should always push US based transactions or risk miscalculating the economic nexus for a state.

**Comment by jarednorman** [comment]
The taxable order check seeks to provide a way to avoid using up your API quota computing tax on orders you know aren't taxable. It is not meant for avoiding pushing transactions to TaxJar, just avoiding computing tax on them using the API.

**Comment by AdnanTheExcellent** [comment]
A couple comments on this:

1. There are reasons to avoid pushing orders, not jsut for API calls to compute tax. I dont know about other stores but at Printivity we have a couple types of orders that we would not want to push to TaxJar. For Example, we create orders for "paper samples" that are essentially $0 orders. These orders do not make any sense to send to taxjar and use up our order transaction quota.
2. It is useful (and recommended) by TaxJar to submit all orders that are > $0, regardless of whether they are taxable. This is necessary for TaxJars Economic Nexus Insights feature which informs you when you hit economic nexus in specific states.

**Comment by Noah-Silvera** [comment]
@AdnanTheExcellent thanks for the insight!

I think I'll rework this ticket into just documenting this configuration, and how you **shouldn't** use it in order to make sure the economic nexus feature will work correcting.

**Comment by Noah-Silvera** [comment]
Moved into a global documentation ticket #207
