### ISSUE TITLE
[bug] solidus_taxjar does not take into account shipment promotion adjustments

### ISSUE THREAD

**Issue by AdnanTheExcellent** [SuperGoodSoft/solidus_taxjar#56]
a quick example order:

1 line item: $100
shipping: $20
tax : $7.75
discount: $20 from free shipping coupon
order total: $107.75

in solidus taxjar the default shipping calculator is:

```ruby
    self.shipping_calculator = ->(order) { order.shipment_total }
```

In the example above, the shipping calculator will return $20 (which doesn't account for promotions), when it should return $0. This will lead to the following taxjar error:

`Taxjar::Error::BadRequest (Order amount must be equal to the sum of line items and shipping)`

since taxjar will see an order total of $107.75 and throw an error when 107.75 != 100 + 20 + 7.75

I propose changing the calculator to the following:

```ruby
    self.shipping_calculator = ->(order) { order.shipment_total + order.shipments.map(&:promo_total).sum }
```

**Comment by jarednorman** [comment]
I'm surprised that I didn't know that `shipment_total` is just the sum of the `cost` columns of the shipments, which is just the cost of their selected shipping methods and nothing else.

I think we might be better off using the `Spree::Shipment#total_before_tax` to capture any other arbitrary adjustments, excluding taxes.

```
    self.shipping_calculator = ->(order) { order.shipments.sum(&:total_before_tax) }
```

**Comment by AdnanTheExcellent** [comment]
> 
> ```ruby
>     self.shipping_calculator = ->(order) { order.shipments.sum(&:total_before_tax) }
> ```

I am fine with this

**Comment by Noah-Silvera** [comment]
@nvandoorn and I are going to tackle this! Dug into it ourselves, seems like a totally reasonable fix. :)
