### ISSUE TITLE
Check if merchant has nexus before calculating tax

### ISSUE THREAD

**Issue by AdnanTheExcellent** [SuperGoodSoft/solidus_taxjar#57]
Now that nexus regions are part of this extension, i want to propose updating the `taxable_address_check` to account for those. something like:

```ruby
    self.taxable_address_check = ->(address) {
      nexus_regions = ::SuperGood::SolidusTaxjar.api.nexus_regions
      nexus_regions.map(&:region_code).include?(address.state.abbr)
    }
```

This follows taxjars best practice as they have outlined in their API technical review:

```
2. API calls only for nexus states with the TaxJar API enabled

... 

Only call for a tax calculation in states where you have nexus
The /v2/nexus/regions endpoint can be used to create a dynamic filter to only call the TaxJar API for a tax calculation for states where you have nexus! This helps to control the number of API calls on a monthly basis!

You can accomplish this by creating a list based on the "region_code" from the response and comparing that to the state code that you would normally pass for the "to_state" in a /v2/taxes call.

Be sure to only pass the two-letter ISO code for the state when requesting a live tax calculation! If the state is passed as the full name, such as Arizona, the lookup will result in an error!
```

**Comment by jarednorman** [comment]
Nice. Good call.

**Comment by Noah-Silvera** [comment]
One thing to note when implementing this is that **All transactions need to be pushed to taxjar regardless of nexus or taxability**, so we can't skip the reporting hook. 

https://developers.taxjar.com/integrations/certification-checklist/#section-sales-tax-reporting-and-filing

**Comment by Noah-Silvera** [comment]
Note - we should double check this is needed for certification before tackling it!

**Comment by Noah-Silvera** [comment]
It is certification requirement! Under Sales Tax Calculations
https://developers.taxjar.com/integrations/certification-checklist/#section-sales-tax-reporting-and-filing

> Only send a request to [v2/taxes](https://developers.taxjar.com/api/reference/#taxes) when a merchant has nexus

Avoid unnecessary API calls to v2/taxes by understanding the concept of <a href="https://blog.taxjar.com/sales-tax-nexus-definition/" target=_blank>sales tax nexus. If a customer's delivery address is not in a state in which a merchant has nexus, no sales tax needs to be collected; therefore, there's no need to calculate tax.
*Keep in mind this only applies to US-based sales. Tax may need to be calculated for other jurisdictions.
