### ISSUE TITLE
Provide client-side logging for support

### ISSUE THREAD

**Issue by nvandoorn** [SuperGoodSoft/solidus_taxjar#63]
From here: https://developers.taxjar.com/integrations/certification-checklist/

> API requests / responses should be logged to a local file or somewhere in the platform for a merchant to view so they can more easily receive support for technical or tax-related issues.

**Comment by nvandoorn** [comment]
Work has been kicked off on the TaxJar Ruby client: https://github.com/taxjar/taxjar-ruby/pull/68

**Comment by Noah-Silvera** [comment]
After further discussion with the TaxJar team, we learned that the above PR will not get merged for likely a long time. However, the most important thing is that the errors that the TaxJar API throws are logged. We can accomplish this by catching all errors thrown by the API and logging them https://developers.taxjar.com/api/reference/#errors

**Comment by Noah-Silvera** [comment]
I did a little bit more research and discovered two things

- The `Taxjar::Error` that is thrown from an HTTP request within the gem contains a HTTP response code and message
- We can assume any other code is a 2XX code as this method is used [https://www.rubydoc.info/github/httprb/http/HTTP%2FResponse%2FStatus:success%3F](https://www.rubydoc.info/github/httprb/http/HTTP%2FResponse%2FStatus:success%3F)
    - But we don’t have the specific code

**Comment by benjaminwil** [comment]
We also need to provide an view and/or export function so that TaxJar customers can more easily receive technical support from the TaxJar customer service team.

Maybe the Rails Logger gets us most of the way there.

**Comment by Noah-Silvera** [comment]
After talking to Ryan, he told us we don't need to worry about log retention export! 🎉

The rails logger will be sufficient

**Comment by Noah-Silvera** [comment]
Adam and I started some work on this here with a basic integration spec

https://github.com/SuperGoodSoft/solidus_taxjar/compare/rails-logging-of-taxjar-endpoints?expand=1

**Comment by Noah-Silvera** [comment]
One problem with this implementation that was raised was that if we hardcode the URL that an internal endpoint is posting to, then we tie ourselves to the internal Taxjar implementation. However, every suggested approach to this problem ties itself to the internal Taxjar implementation sadly.
