### ISSUE TITLE
Generator Not Found

### ISSUE THREAD

**Issue by jakemumu** [SuperGoodSoft/solidus_taxjar#67]
Just added this to a fairly fresh solidus app:

```
gem 'solidus', '2.11.5'
gem 'solidus_auth_devise'
gem 'super_good-solidus_taxjar'
gem 'solidus_paypal_commerce_platform'
```

After trying to run the generator: 

`bundle exec rails g super_good:solidus_taxjar:install`

result:

`Could not find generator 'super_good:solidus_taxjar:install'`

Upon looking in the gem I'm not seeing this generator although I'm not an expert here : )

**Comment by jakemumu** [comment]
scratch these -- seems like generator nor migrations are necessary for this Gem anymore? Might be worth updating the readme : )

**Comment by Noah-Silvera** [comment]
@jakemumu this is a mistake - there is actually no generator or migrations that are necessary, the readme is mistaken. We will remove that instruction from the readme!

**Comment by nvandoorn** [comment]
Hey @jakemumu, thanks for reporting this. #68 has been merged to remove the incorrect instructions.
