### ISSUE TITLE
Setup documentation website

### ISSUE THREAD

**Issue by nvandoorn** [SuperGoodSoft/solidus_taxjar#72]
We need administrator facing documentation that goes beyond just some markdown files in the repository.

For reference, here are the Magento TaxJar docs: https://www.taxjar.com/guides/integrations/magento2/#how-reporting-works

**Comment by Noah-Silvera** [comment]
Closing this because Ryan clarified that for now, markdown files in the repository are sufficient - we don't need a full documentation site.
