### ISSUE TITLE
Support admin UI for enabling/disabling reporting

### ISSUE THREAD

**Issue by nvandoorn** [SuperGoodSoft/solidus_taxjar#73]
After this extensions supports reporting, we need an admin UI to enable/disable it.

See more here: https://developers.taxjar.com/integrations/sales-tax-reporting/#section-ux-guidelines

**Acceptance Criteria:**

* [ ] An input to enable/disable reporting should be added to the [taxjar settings page](https://github.com/SuperGoodSoft/solidus_taxjar/blob/master/app/views/spree/admin/taxjar_settings/show.html.erb).
* [ ] It should change the [`reporting_enabled` configuration option](https://github.com/SuperGoodSoft/solidus_taxjar/pull/103).
* [ ] A feature spec should be added to test this behavior.

**Comment by Noah-Silvera** [comment]
@senemsoy this could also be a good one for you!

**Comment by Noah-Silvera** [comment]
Pretty sure this was completed with #138
