### ISSUE TITLE
Assign products to a tax category

### ISSUE THREAD

**Issue by nvandoorn** [SuperGoodSoft/solidus_taxjar#74]
TaxJar provides a list of categories for different products from their API. Users should be able to select their products tax category from a dropdown.

Note that the tax categories can be fetched ahead of time and then synced, or grabbed on demand.

**Comment by jarednorman** [comment]
Keep in mind that Solidus has a concept of tax category.

**Comment by benjaminwil** [comment]
We think that we can just map Solidus tax categories to TaxJar tax categories.

**Comment by benjaminwil** [comment]
There's a TaxJar endpoint that lets us pull its tax categories.

**Comment by Noah-Silvera** [comment]
Ryan recommended we re-sync Tax Categories at least every 30-60 days. We could probably even do it on a more regular basis if it's a cheap operation.

He also told us that we can reasonably expect that existing Tax Categories will not change or be deleted

**Comment by benjaminwil** [comment]
Since we merged #183, you can use the admin UI to associate a TaxJar tax code with a `Spree::TaxCategory` record, for its `#tax_category` field.

For each line item we send to the TaxJar API, we send this tax code.
