### ISSUE TITLE
Doesn't Support Order Adjustments?

### ISSUE THREAD

**Issue by jakemumu** [SuperGoodSoft/solidus_taxjar#78]
I'm facing an issue with this extensions -- it appears line item adjustments properly are removed from the taxable amount, but order adjustments are not. Is there a way to fix that? 

Thanks, 

J

**Comment by jarednorman** [comment]
Don't use order-level adjustments. 😅 

There's no way for the extension to know how to distribute their amounts across the items in the order correctly, which can cause you to misrepresent and incorrectly report your taxes to TaxJar. As matter of best practices in eCommerce in general, order-level adjustments are a bad idea that can cause headaches when it comes to accounting and should generally be avoided.

**But...** we actually do have a solution for this. Use [this extension point](https://github.com/SuperGoodSoft/solidus_taxjar/blob/master/lib/super_good/solidus_taxjar.rb#L41) to implement a discount calculator that follows whatever rules makes sense for how you're using order-level adjustments. We're very aware that in practice many people do use them so we created that extension point to solve that need. 😄

I hope that helps and thanks for raising this issue. I'm sure it'll be helpful for others who run into this same issue.

**Comment by aldesantis** [comment]
I just had to solve this problem in a project, and here's the discount calculator we implemented:
```ruby
class DiscountCalculator
  def initialize(line_item)
    @line_item = line_item
  end

  def discount
    -(line_item_discount + order_discount)
  end

  def line_item_discount
    line_item.adjustments.credit.eligible.sum(:amount)
  end

  def order_discount
    Spree::DistributedAmountsHandler.new(
      order.line_items,
      order.adjustments.credit.eligible.sum(:amount),
    ).amount(line_item)
  end

  private

  attr_reader :line_item

  def order
    line_item.order
  end
end
```
Note that this works well for us because all of our products belong to the same tax category.

If you have products that belong to multiple tax categories, I'd strongly advise using adjustments at the line item level instead, because discounting a product with a 1% sales tax is different from discounting a product with a 6% sales tax.
