### ISSUE TITLE
Implement "create_refund" interface to be used for full order refunds

### ISSUE THREAD

**Issue by benjaminwil** [SuperGoodSoft/solidus_taxjar#91]
# What

Create a new `create_full_order_refund_for(taxjar_transaction_id)` action that

1. Creates a refund for a transaction that mirrors the transaction amounts.
2. Inverts the amounts (i.e. `$1.99` becomes `-$1.99`).
3. Posts the refund transaction and "cancels out" the original transaction.

## Requirements

- The `transaction_id` of the refund should be the `solidus_order.order_number + “-REFUND”`.
- The `transaction_reference_id` should be the referenced `transaction_id`. (The argument of the method, likely.)
- The following values should be inverted to completely "cancel out" the referenced transaction's values:
   - `amount`
   -  `shipping`
   -  `sales_tax`
   -  `line_items[].unit_price`
   -  `line_items[].sales_tax`
    
  We cannot use the Solidus values for the refund, because the `solidus_order` amounts will have changed. We will use the `solidus_order` amounts to create the new transaction, though.

# Why

The current `create_refund_for(reimbursement)` method is not quite what we need to "update" transactions that have been changed.

**Comment by benjaminwil** [comment]
`-REFUND` is just a suggestion. As is the name of the method I've provided.

**Comment by Noah-Silvera** [comment]
This was completed with the work in #100 . However, the method is called `create_refund_transaction_for`
