### ISSUE TITLE
Conditionally "update" transactions on `order_recalculated` events

### ISSUE THREAD

**Issue by benjaminwil** [SuperGoodSoft/solidus_taxjar#92]
# What

First, we subscribe to all of the order's  `order_recalculated` events. 

Second, we check if a recalculated order is eligible to re-send a transaction to TaxJar. We need to:

1. Check that the current order is `paid` and `complete`.
2. Determine whether a TaxJar transaction already exists for the current order.
   (Blocked by #89 and #101)

Then, if the transaction meets the above criteria:

- If the `transaction_params(solidus_order)` matches what is in the existing TaxJar transaction:
  - Do nothing.
- If the `transaction_params(solidus_order)` do not match what is in the existing TaxJar transaction:
  - Update the taxjar transaction using the custom refund/create logic #112
- If a transaction doesn't exist:
    - Create a new transaction for the order with the latest amounts.

The top-level of this decision tree can be handled by a service that checks whether TaxJar has the most up-to-date order information. (#106.)

# Why

It's impossible to `PUT` updates to transactions when they're in a tax period that has closed. Posting refunds and new orders makes tax reporting more straightforward for TaxJar end users.

This issue covers the following flows in stock Solidus:

- New or updated line item adjustments
- New or updated order-level adjustments
- New or updated shipment adjustments
- New promotion adjustments
- New reimbursements (refunds or store credit)
- New line item cancellations

We could break down this issue into further sub-tasks, but we thought it was worthwhile to provide the big-picture flow.

**Comment by Noah-Silvera** [comment]
We are going to make the assumption it is safe to assume all paid orders are also complete - we should filter on complete orders.
We should **very clearly** document that **only complete** orders will be pushed to TaxJar

**Comment by Noah-Silvera** [comment]
Idea: we could allow users to configure the states of an order that are checked for it to be created/updated.

**Comment by Noah-Silvera** [comment]
Notes from investigating how "paid" orders work in solidus

The `def paid?` method on the order returns true if the `payment_state` is `paid` **OR** `credit_owed`. We want to ignore `credit_owed` so we can't used `paid?`, we have to directly use the `payment_state`

@alexblackie and I confirmed with investigation that the `payment_state` only goes to paid when the order is **captured** and not just when it is authorized.

**Comment by forkata** [comment]
> The `def paid?` method on the order returns true if the `payment_state` is `paid` **OR** `credit_owed`. We want to ignore `credit_owed` so we can't used `paid?`, we have to directly use the `payment_state`

Great investigation @Noah-Silvera. If the order is in `credit_owed` stat that could mean that we've collected the payment from the customer already, we've just over-collected 🤔 I know initially we said we're going to use the `paid` state in order to reduce the number of times we refund and re-create the transaction, but we should probably document that decision as we're going to be deferring the transaction creation until the order is balanced.

**Comment by benjaminwil** [comment]
We've resolved this issue in the referenced merged PRs.
